/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.mml.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.mydsl.mml.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MmlFactoryImpl extends EFactoryImpl implements MmlFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static MmlFactory init()
  {
    try
    {
      MmlFactory theMmlFactory = (MmlFactory)EPackage.Registry.INSTANCE.getEFactory(MmlPackage.eNS_URI);
      if (theMmlFactory != null)
      {
        return theMmlFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new MmlFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MmlFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case MmlPackage.MML_MODEL: return createMMLModel();
      case MmlPackage.DATA_INPUT: return createDataInput();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MMLModel createMMLModel()
  {
    MMLModelImpl mmlModel = new MMLModelImpl();
    return mmlModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataInput createDataInput()
  {
    DataInputImpl dataInput = new DataInputImpl();
    return dataInput;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MmlPackage getMmlPackage()
  {
    return (MmlPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static MmlPackage getPackage()
  {
    return MmlPackage.eINSTANCE;
  }

} //MmlFactoryImpl
