/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MmlGrammarAccess extends AbstractGrammarElementFinder {
	
	public class MMLModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Mml.MMLModel");
		private final Assignment cInputAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cInputDataInputParserRuleCall_0 = (RuleCall)cInputAssignment.eContents().get(0);
		
		//MMLModel:
		//	input=DataInput;
		@Override public ParserRule getRule() { return rule; }
		
		//input=DataInput
		public Assignment getInputAssignment() { return cInputAssignment; }
		
		//DataInput
		public RuleCall getInputDataInputParserRuleCall_0() { return cInputDataInputParserRuleCall_0; }
	}
	public class DataInputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Mml.DataInput");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInputKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cFilelocationAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cFilelocationSTRINGTerminalRuleCall_1_0 = (RuleCall)cFilelocationAssignment_1.eContents().get(0);
		
		//DataInput:
		//	'input' filelocation=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'input' filelocation=STRING
		public Group getGroup() { return cGroup; }
		
		//'input'
		public Keyword getInputKeyword_0() { return cInputKeyword_0; }
		
		//filelocation=STRING
		public Assignment getFilelocationAssignment_1() { return cFilelocationAssignment_1; }
		
		//STRING
		public RuleCall getFilelocationSTRINGTerminalRuleCall_1_0() { return cFilelocationSTRINGTerminalRuleCall_1_0; }
	}
	
	
	private final MMLModelElements pMMLModel;
	private final DataInputElements pDataInput;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MmlGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pMMLModel = new MMLModelElements();
		this.pDataInput = new DataInputElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.Mml".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//MMLModel:
	//	input=DataInput;
	public MMLModelElements getMMLModelAccess() {
		return pMMLModel;
	}
	
	public ParserRule getMMLModelRule() {
		return getMMLModelAccess().getRule();
	}
	
	//DataInput:
	//	'input' filelocation=STRING;
	public DataInputElements getDataInputAccess() {
		return pDataInput;
	}
	
	public ParserRule getDataInputRule() {
		return getDataInputAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
