/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.mml;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.mml.MmlPackage
 * @generated
 */
public interface MmlFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MmlFactory eINSTANCE = org.xtext.example.mydsl.mml.impl.MmlFactoryImpl.init();

  /**
   * Returns a new object of class '<em>MML Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MML Model</em>'.
   * @generated
   */
  MMLModel createMMLModel();

  /**
   * Returns a new object of class '<em>Data Input</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Input</em>'.
   * @generated
   */
  DataInput createDataInput();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MmlPackage getMmlPackage();

} //MmlFactory
