/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.mml;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.mml.MmlFactory
 * @model kind="package"
 * @generated
 */
public interface MmlPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mml";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Mml";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mml";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MmlPackage eINSTANCE = org.xtext.example.mydsl.mml.impl.MmlPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.MMLModelImpl <em>MML Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.MMLModelImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getMMLModel()
   * @generated
   */
  int MML_MODEL = 0;

  /**
   * The feature id for the '<em><b>Input</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MML_MODEL__INPUT = 0;

  /**
   * The number of structural features of the '<em>MML Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MML_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mml.impl.DataInputImpl <em>Data Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mml.impl.DataInputImpl
   * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getDataInput()
   * @generated
   */
  int DATA_INPUT = 1;

  /**
   * The feature id for the '<em><b>Filelocation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_INPUT__FILELOCATION = 0;

  /**
   * The number of structural features of the '<em>Data Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_INPUT_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.MMLModel <em>MML Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MML Model</em>'.
   * @see org.xtext.example.mydsl.mml.MMLModel
   * @generated
   */
  EClass getMMLModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mml.MMLModel#getInput <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Input</em>'.
   * @see org.xtext.example.mydsl.mml.MMLModel#getInput()
   * @see #getMMLModel()
   * @generated
   */
  EReference getMMLModel_Input();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mml.DataInput <em>Data Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Input</em>'.
   * @see org.xtext.example.mydsl.mml.DataInput
   * @generated
   */
  EClass getDataInput();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mml.DataInput#getFilelocation <em>Filelocation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Filelocation</em>'.
   * @see org.xtext.example.mydsl.mml.DataInput#getFilelocation()
   * @see #getDataInput()
   * @generated
   */
  EAttribute getDataInput_Filelocation();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MmlFactory getMmlFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.MMLModelImpl <em>MML Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.MMLModelImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getMMLModel()
     * @generated
     */
    EClass MML_MODEL = eINSTANCE.getMMLModel();

    /**
     * The meta object literal for the '<em><b>Input</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MML_MODEL__INPUT = eINSTANCE.getMMLModel_Input();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mml.impl.DataInputImpl <em>Data Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mml.impl.DataInputImpl
     * @see org.xtext.example.mydsl.mml.impl.MmlPackageImpl#getDataInput()
     * @generated
     */
    EClass DATA_INPUT = eINSTANCE.getDataInput();

    /**
     * The meta object literal for the '<em><b>Filelocation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_INPUT__FILELOCATION = eINSTANCE.getDataInput_Filelocation();

  }

} //MmlPackage
